"""Precio tipo de dato

Revision ID: 463bbb468cfe
Revises: 856e297804f4
Create Date: 2024-06-24 14:19:47.361903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463bbb468cfe'
down_revision = '856e297804f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_referenciala', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.drop_column('precio_referenciala')

    # ### end Alembic commands ###
