"""Precio tipo de datos

Revision ID: 8331111a9a70
Revises: 463bbb468cfe
Create Date: 2024-06-24 14:20:51.730447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8331111a9a70'
down_revision = '463bbb468cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.alter_column('precio_referencial',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.alter_column('precio_referencial',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
