"""Precios

Revision ID: 8953db097eb5
Revises: acd9a0cb0aef
Create Date: 2024-06-24 14:37:09.317966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8953db097eb5'
down_revision = 'acd9a0cb0aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_referencial', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('precio_referenciala')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_referenciala', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('precio_referencial')

    # ### end Alembic commands ###
