"""Visitas

Revision ID: f653bd4c66f8
Revises: 8953db097eb5
Create Date: 2024-07-01 20:32:41.872217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f653bd4c66f8'
down_revision = '8953db097eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_visita', sa.Date(), nullable=False),
    sa.Column('valoracion', sa.Integer(), nullable=False),
    sa.Column('reseña', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_visita')
    op.drop_table('visita')
    # ### end Alembic commands ###
